language: php

php:
    - '7.2'
    - '7.3'

sudo: false

before_script:
    - composer self-update && composer install

script:
    - mkdir -p build/log
    - vendor/bin/phpcs -ps
    - vendor/bin/phpunit -c phpunit.xml.dist

after_success:
    - travis_retry php vendor/bin/php-coveralls
